

BASE:
 #log等级
 log_level: "debug"
 #扩展名
 log_extension: ".log"
 test:
  url: "http://47.94.239.71"
  case_file: "testdata.xlsx"
  case_sheet: "接口测试"


email:
 smtpserver: "smtp.qq.com"
 username: "103805697@qq.com"
 password: "yqlevfptbqwlcagi"
 receiver: "103805697@qq.com"
